// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (i *Item) Vendors(ctx context.Context) (*Vendor, error) {
	result, err := i.Edges.VendorsOrErr()
	if IsNotLoaded(err) {
		result, err = i.QueryVendors().Only(ctx)
	}
	return result, err
}

func (v *Vendor) Item(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = v.NamedItem(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = v.Edges.ItemOrErr()
	}
	if IsNotLoaded(err) {
		result, err = v.QueryItem().All(ctx)
	}
	return result, err
}
